# The address that you use to access the TrueNAS Web UI over HTTPS.
# This MUST be the HTTPS address, not the HTTP address!
# This is compatible with Tailscale or other similar VPN solutions.
truenas_host = "192.168.1.xxx:443"

# The service name of the secret in the keyring/secrets manager.
# This is different across OSes, see docs.
# (Default: "truenas")
# secrets_manager_service_field = "truenas"

# The uername field of the secret in the keyring/secrets manager.
# This is different across OSes, see docs.
# (Default: "api-key")
# secrets_manager_username_field = "api-key"

# WARNING: Storing API keys in plain text is a security risk.
# Recommended to use your OS's secrets manager instead. See docs.
# api_key = "1234567890"

# WARNING: This is only intended for future-proofing, in case the API route ever 
# changes. This must match what TrueNAS currently uses. (Default: "/api/current")
# api_route = "/api/current"

# Setting log level is equivalent to setting the --verbose flag on the CLI.
# -v = warning, -vv = info, -vvv = debug
# Values: [critical, error, warning, info, debug]  (Default: "error")
# log_level = "error"

# For debugging/development. If program crashes, print a rich traceback to console.
# rich_traceback = true