# The address that you use to access the TrueNAS Web UI over HTTPS, without
# the "https://" prefix. This MUST be the HTTPS address, not the HTTP address!
# You MUST have HTTPS enabled on the TrueNAS Web UI to use the TrueNAS API.
# If you use a port number you must include it, like "192.168.1.xxx:443".
truenas_host = "192.168.1.xxx:443"

# The path to the TrueNAS certificate file. This is required if you use a
# self-signed certificate. If you use a certificate signed by a trusted CA,
# you can leave this blank. Alternatively, you can set validate_certs to False.
# truenas_cert_path = "/path/to/cert.crt"

# Set this to True to skip certificate validation. This is not recommended, as its
# better to use a self-signed certificate. However, this does allow you to use
# this program without having a certificate on your machine. (Default: true)
# validate_certs = true

# WARNING: Storing API keys in plain text is a security risk.
# Recommended to use one of the other methods such as your OS's secrets manager,
# or creating an environment variable called TRUENAS_API_KEY. See docs.
# api_key = "1234567890"

# WARNING: This is only intended for future-proofing, in case the API route ever 
# changes. This must match what TrueNAS currently uses. (Default: "/api/current")
# api_route = "/api/current"

# How often to poll the TrueNAS API for updates, in seconds. (Default: 10)
polling_interval = 10

# Setting log level to info or debug is equivalent to using the --verbose flag
# on the CLI. -v = info, -vv = debug, -vvv = trace
# Options: [critical, error, warning, info, debug, trace]  (Default: "warning")
# log_level = "warning"

# Set to true to disable color output. This is equivalent to using the
# --no-color flag on the CLI.
no_color = false